Iter9
Meduzza143/metric2 pull request #2
Opened 2023-11-01 16:48 UTC by Meduzza143

2023-11-13 07:10 UTC, edylcrm requested changes

2023-11-13 07:10 UTC, edylcrm commented on internal/serializer/serializer.go
> +func (*MetricsJSON) Deserialize(req *http.Request) (metric storage.MemStruct, er error) {
[LINT] можно использовать подход ранний return и писать код чуть-чуть проще.
```
func (*MetricsJSON) Deserialize(req *http.Request) (storage.MemStruct, error) {
	body, err := io.ReadAll(req.Body)
	if err != nil {
		return storage.MemStruct{}, err
	}

	defer req.Body.Close()

	var mj MetricsJSON
	err = json.Unmarshal(body, &mj)
	if err != nil {
		return storage.MemStruct{}, err
	}
	metric := storage.MemStruct{}

	if mj.ID != "" {
		metric.MetricName = mj.ID
	}
	if mj.MType != "" {
		metric.MetricType = mj.MType
	}
	if mj.Value != nil {
		metric.GaugeValue = *mj.Value
	}
	if mj.Delta != nil {
		metric.CounterValue = *mj.Delta
	}

	return metric, nil
}
```

2023-11-13 07:10 UTC, edylcrm commented on internal/server/controllers/saveLoader.go
> +var saveLoader *SaveLoader = nil
[LINT] вообще весь этот подход с синглтонами плохая практика, лучше так не делать.

2023-11-13 07:10 UTC, edylcrm commented on internal/server/controllers/saveLoader.go
> +		for s.keepRunning {
[BLOCKER] все таки здесь учимся писать на golang и использовать его подходы.
Не нужно использовать bool переменные для отслеживания состояния. Для этого есть context на который и стоит здесь завязаться. И не использовать time.Sleep(), а использовать каналы.
```
func (s *SaveLoader) Run(ctx context.Context) {
	if s.interval > 0 {
		return 
	}
	
	t := time.NewTicker(s.interval)
	for {
		select {
			case <- t.C:
				s.SaveAll()
			case <- ctx.Done():
				s.file.Close()
				return
		}
	}
}
```

2023-11-13 07:10 UTC, edylcrm commented on internal/server/controllers/saveLoader.go
> +	if err == nil {
[LINT] здесь так же можно сделать ранний return

2023-11-13 07:10 UTC, edylcrm commented on internal/server/controllers/saveLoader.go
> +	if len(mem) > 0 {
[LINT] и здесь ранний return

2023-11-13 07:10 UTC, edylcrm commented on internal/server/handlers/handlers.go
> +var answer []byte
[BLOCKER] выглядит не очень. В этом месте лучше использовать подход DI для большинства этих var

2023-11-13 07:10 UTC, edylcrm commented on internal/server/handlers/handlers.go
> +	if status == http.StatusOK { //ok
[LINT] ранний return

2023-11-13 07:10 UTC, edylcrm commented on internal/server/handlers/handlers.go
> +				status = http.StatusNotFound
[LINT] и тут

2023-11-13 08:17 UTC, Meduzza143 commented on internal/server/handlers/handlers.go
> +	if status == http.StatusOK { //ok
Здесь точно можно ? Суть в том что тут заполняются параметры с которыми в конечном итоге вызовется универсальный ResponseWriter. Нам ведь в любом случае нужно что-то ответить клиенту...

2023-11-13 08:18 UTC, Meduzza143 commented on internal/server/handlers/handlers.go
> +				status = http.StatusNotFound
Аналогично, данные уходят в ResponseWriter

2023-11-13 08:19 UTC, Meduzza143 commented on internal/serializer/serializer.go
> +func (*MetricsJSON) Deserialize(req *http.Request) (metric storage.MemStruct, er error) {
+

2023-11-13 08:19 UTC, Meduzza143 commented on internal/server/controllers/saveLoader.go
> +	if err == nil {
+

2023-11-13 08:19 UTC, Meduzza143 commented on internal/server/controllers/saveLoader.go
> +	if len(mem) > 0 {
+

2023-11-14 05:55 UTC, edylcrm approved these changes

2023-11-14 07:02 UTC, merged